name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 15 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install sqlite-utils globally
      run: pip install sqlite-utils

    - name: Run ytscraper.py
      run: YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }} python3 ytscraper.py

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "turnerdalton055@gmail.com"
        git config --global user.name "daltonturner"
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated update on ${timestamp}" || exit 0
        git push https://github.com/daltonturner/MSSPScraper

