name: Vercel Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Scraper"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Datasette using Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel video_data.db \
          --token $VERCEL_TOKEN \
          --project mssp-scraper \
          --metadata metadata.json
